
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const menuToggle=$("#menuToggle"),nav=$("#nav");menuToggle?.addEventListener("click",()=>{nav.classList.toggle("open");menuToggle.innerHTML=nav.classList.contains("open")?'<i class="fa-solid fa-xmark"></i>':'<i class="fa-solid fa-bars"></i>'});$$('.nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const modal=$("#turnModal");function openModal(){modal?.classList.add('open');document.body.style.overflow='hidden'}function closeModal(){modal?.classList.remove('open');document.body.style.overflow=''}$$('[data-turnos]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();openModal()}));$$('[data-close]').forEach(b=>b.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
const back=$("#backTop");window.addEventListener('scroll',()=>back?.classList.toggle('show',scrollY>500));back?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
const slides=$$('.hero__slide'),dots=$$('.hero__dot'),progress=$("#heroProgress");let current=0,timer;function show(i){current=(i+slides.length)%slides.length;slides.forEach((s,n)=>s.classList.toggle('active',n===current));dots.forEach((d,n)=>d.classList.toggle('active',n===current));if(progress){progress.classList.remove('run');void progress.offsetWidth;progress.classList.add('run')}}function start(){clearInterval(timer);timer=setInterval(()=>show(current+1),5000)}if(slides.length){show(0);start();$('.hero__arrow.next')?.addEventListener('click',()=>{show(current+1);start()});$('.hero__arrow.prev')?.addEventListener('click',()=>{show(current-1);start()});dots.forEach((d,i)=>d.addEventListener('click',()=>{show(i);start()}));let sx=0;$('.hero')?.addEventListener('touchstart',e=>sx=e.changedTouches[0].screenX,{passive:true});$('.hero')?.addEventListener('touchend',e=>{let dx=e.changedTouches[0].screenX-sx;if(Math.abs(dx)>45){show(dx<0?current+1:current-1);start()}},{passive:true})}
$$('[data-demo-form]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const msg=f.querySelector('[data-form-msg]');if(msg){msg.textContent='¡Solicitud registrada! Este formulario es una demostración y queda listo para conectarlo al sistema real del hospital.';msg.style.color='#087b5a'}f.reset()}));
const y=$("#year");if(y)y.textContent=new Date().getFullYear();

// V14 — dropdown Institucional
$$('.nav-dropdown__toggle').forEach(btn=>btn.addEventListener('click',e=>{e.preventDefault();const box=btn.closest('.nav-dropdown');const isOpen=box.classList.toggle('open');$$('.nav-dropdown').forEach(other=>{if(other!==box){other.classList.remove('open');other.querySelector('.nav-dropdown__toggle')?.setAttribute('aria-expanded','false')}});btn.setAttribute('aria-expanded',String(isOpen));}));
document.addEventListener('click',e=>{$$('.nav-dropdown.open').forEach(box=>{if(!box.contains(e.target)){box.classList.remove('open');box.querySelector('.nav-dropdown__toggle')?.setAttribute('aria-expanded','false')}})});
$$('.nav-dropdown__menu a').forEach(a=>a.addEventListener('click',()=>{nav?.classList.remove('open');$$('.nav-dropdown.open').forEach(box=>box.classList.remove('open'))}));
